add output_dir parameter
vanvalenlab/kiosk-client pull request #66
Opened 2020-09-01 17:07 UTC by omerbt

Added an optional parameter: output_dir. if provided, DeepCell output will be saved in that directory.

2020-09-19 13:55 UTC, omerbt commented
I updated the code according to the comments

2020-09-21 23:14 UTC, willgraf requested changes
Love the tests! Just one more style-related suggested change. This project uses single quotes (`'`) for strings and double quotes (`"`) for docstrings.

2020-09-21 23:14 UTC, willgraf commented on kiosk_client/job.py
> +                             " %s is not writable" % self.output_dir)
```suggestion
            raise ValueError('Invalid value for output_dir,'
                             ' %s is not a directory.' % self.output_dir)
        if not os.access(self.output_dir, os.W_OK):
            raise ValueError('Invalid value for output_dir,'
                             ' %s is not writable.' % self.output_dir)
```

2020-09-21 23:14 UTC, willgraf commented on kiosk_client/manager.py
> +                             " %s is not writable" % self.output_dir)
```suggestion
        if not os.path.isdir(self.output_dir):
            raise ValueError('Invalid value for output_dir,'
                             ' %s is not a directory.' % self.output_dir)
        if not os.access(self.output_dir, os.W_OK):
            raise ValueError('Invalid value for output_dir,'
                             ' %s is not writable.' % self.output_dir)
```

2020-09-22 07:23 UTC, omerbt commented
great thanks!

2020-09-22 16:22 UTC, willgraf approved these changes

2020-09-22 16:23 UTC, merged